name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
#    - name: Set up OS
#      run: |
#        safaridriver --enable
    - name: Install dependencies
      run: |
        npm install selenium-webdriver
        npm install http-server
    - name: Run tests
      run: |
        cd /Users/runner/work/soundstage/
        http-server -a localhost -p 80
        cd soundstage/
        node ./test.js
#        npx selenium-webdriver
