name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up OS
      run: |
        safaridriver --enable
    - name: Install dependencies
      run: |
        npm install selenium-webdriver
    - name: Run tests
      run: |
        npm run test.js
#        npx selenium-webdriver
