name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: stephband/fn
        path: fn/
    - uses: actions/checkout@v3
      with:
        repository: stephband/dom
        path: dom/
    - uses: actions/checkout@v3
    - name: Set up OS
      run: |
        sudo safaridriver --enable
    - name: Install dependencies
      run: |
        npm install selenium-webdriver
    - name: Run tests
      run: |
        cd ../
        ls -l
        python -m SimpleHTTPServer 8000 &
        cd soundstage/
        node ./.github/workflows/tests.js
