name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up OS
      run: |
        sudo safaridriver --enable
    - name: Install dependencies
      with:
        repository: stephband/fn
        #path: resources/docs/2.x
        #ref: 2.x
      run: |
        npm install selenium-webdriver
    - name: Run tests
      run: |
        cd ../
        python -m SimpleHTTPServer 8000 &
        cd soundstage/
        node ./.github/workflows/tests.js
#        npx selenium-webdriver
