name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Set up OS
      run: |
        sudo safaridriver --enable
    - name: Clone fn
      uses: actions/checkout@v3
      with:
        repository: stephband/fn
        path: fn/
    - name: Clone dom
      uses: actions/checkout@v3
      with:
        repository: stephband/dom
        path: dom/
    - name: Clone soundstage
      uses: actions/checkout@v3
      with:
        path: soundstage/
    - name: Install Selenium
      run: |
        cd soundstage/
        npm install selenium-webdriver
    - name: Run tests
      run: |
        ls -l
        python -m SimpleHTTPServer 8000 &
        cd soundstage/
        node .github/workflows/tests.js chrome
